CREATE TABLE IF NOT EXISTS usuarios (
    id: SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    lastname VARCHAR(400)
)

CREATE TABLE IF NOT EXISTS task(
    id SMALLINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(250) NOT NULL,
    priority BOOLEAN,
    user_is SMALLINT NOT NULL,
     user_is SMALLINT NOT NULL,
    FOREIGN KEY user_id REFERENCES user(id)
);

